In [2]:
%load_ext autoreload 
%autoreload 2

In [3]:
import seaborn as ss
import numpy as np
from manager.data import DataManager
from factory.classfication_factory import ClassificationFactory
from factory.regression_factory import RegressionFactory
from constants.classification_models import ClassificationModels
from constants.regression_models import RegressionModels



In [4]:
data_manager = DataManager(min_sample_label=10)

data, x_train, x_val, t_train, t_val, = data_manager.get_data()

# accorderie = [[633, 6865, 10, 0, 0.02, 4.04, 0.05, 4.86, 0.06, 75.33]]
accorderie = np.array([[0,100.0,500.0,7.0,0.0,0.0505050505050505,3.263549415515409,0.124,5.24,0.153466632043625,61.42,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,4.0,2.0,2.0,1.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,3.0,2.0,2.0,1.0,4.0,2.0,2.0,1.0,11.0,6.0,6.0,3.0,2.0,1.0,2.0,1.0,2.0,1.0,6.0,3.0,4.0,2.0,2.0,1.0,2.0,1.0,6.0,3.0,4.0,2.0,7.0,4.0,2.0,1.0,2.0,1.0,4.0,2.0,4.0,2.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,4.0,2.0,6.0,3.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,3.0,2.0,6.0,3.0,2.0,1.0,4.0,2.0,2.0,1.0,4.0,2.0,8.0,4.0,5.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,8.0,4.0,7.0,4.0,4.0,2.0,2.0,1.0,2.0,1.0,7.0,4.0,4.0,2.0,9.0,5.0,6.0,3.0,4.0,2.0,6.0,3.0,10.0,5.0,2.0,1.0,6.0,3.0,4.0,2.0,4.0,3.0,4.0,2.0,4.0,2.0,4.0,2.0,6.0,3.0,2.0,1.0,2.0,1.0,10.0,5.0,4.0,2.0,6.0,3.0,8.0,4.0,8.0,4.0,14.0,7.0,12.0,6.0,4.0,2.0,4.0,2.0,8.0,4.0,6.0,3.0,8.0,4.0,4.0,2.0,4.0,2.0,4.0,2.0,4.0,2.0,11.0,6.0,2.0,1.0,10.0,5.0,6.0,3.0,7.0,4.0,6.0,3.0,6.0,3.0,2.0,1.0,2.0,1.0,8.0,4.0,8.0,4.0,10.0,5.0,6.0,3.0,9.0,5.0,7.0,4.0,10.0,5.0,9.0,5.0,4.0,2.0,14.0,7.0,10.0,5.0,4.0,2.0,6.0,3.0,2.0,1.0,8.0,4.0,6.0,3.0,8.0,4.0,4.0,2.0,6.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,6.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,8.0,5.0,7.0,4.0,14.0,7.0,6.0,3.0,6.0,3.0,10.0,5.0,14.0,8.0,11.0,6.0,2.0,1.0,6.0,3.0,14.0,7.0,8.0,4.0,6.0,3.0,2.0,1.0,6.0,3.0,13.0,7.0,5.0,3.0,5.0,3.0,12.0,7.0,8.0,4.0,12.0,6.0,8.0,4.0,8.0,4.0,15.0,8.0,10.0,5.0,12.0,6.0,8.0,4.0,11.0,6.0,10.0,5.0,6.0,3.0,11.0,6.0,9.0,5.0,11.0,6.0,2.0,1.0,14.0,7.0,2.0,1.0,2.0,1.0,4.0,2.0,8.0,4.0,8.0,4.0,8.0,4.0,8.0,4.0,2.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.333333333333333,0.3333333333333333,0.7777777777777777,0.3333333333333333,0.0,1.0,0.0,2.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.09090909090909091,0.0,0.6363636363636364,0.0,1.333333333333333,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.142857142857143,0.5,0.9047619047619048,0.1428571428571429,0.0,0.4285714285714285,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.333333333333333,0.3333333333333333,0.7777777777777777,0.3333333333333333,0.0,1.0,0.0,2.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.2,0.2,0.8666666666666666,0.2,0.0,0.8,0.0,1.666666666666667,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.111111111111111,0.1111111111111111,0.9259259259259258,0.1111111111111111,0.0,0.6666666666666666,0.0,1.4,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.5,0.5,0.625,0.25,0.0,1.5,0.0,3.333333333333333,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.090909090909091,0.5,0.9393939393939393,0.09090909090909091,0.0,0.5454545454545454,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.5555555555555556,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.4444444444444444,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.25,0.125,0.8333333333333333,0.125,0.0,0.625,0.0,1.4,1.142857142857143,0.1428571428571428,0.9047619047619049,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.142857142857143,0.07142857142857142,0.9047619047619048,0.07142857142857142,0.0,0.6428571428571429,0.0,1.25,1.090909090909091,0.5,0.9393939393939393,0.09090909090909088,0.0,0.4545454545454545,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.076923076923077,0.07692307692307693,0.9487179487179487,0.07692307692307691,0.0,0.6153846153846154,0.0,1.285714285714286,1.2,0.5,0.8666666666666666,0.2,0.0,0.4,0.0,1.0,1.2,0.2,0.8666666666666666,0.2,0.0,0.8,0.0,1.666666666666667,1.166666666666667,0.1666666666666667,0.875,0.08333333333333333,0.0,0.8333333333333334,0.0,2.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.066666666666667,0.06666666666666667,0.9555555555555555,0.06666666666666668,0.0,0.6,0.0,1.25,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.090909090909091,0.5,0.9393939393939393,0.09090909090909088,0.0,0.4545454545454545,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.09090909090909088,0.0,0.6363636363636364,0.0,1.333333333333333,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.5555555555555556,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.0909090909090909,0.0,0.6363636363636364,0.0,1.333333333333333,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0]])


training_set_size = x_train.shape[1]
accorderie_size = np.array(accorderie).shape[1]

if training_set_size > accorderie_size:
    diff = training_set_size - accorderie_size
    accorderie = np.array([np.concatenate([accorderie[0],np.zeros(diff)])])
else:
    accorderie = np.array([accorderie[0][:x_train.shape[1]]])

print(accorderie.shape, x_train.shape)



(1, 1038) (880, 1038)


In [13]:
model = RegressionFactory.get_model(RegressionModels.ELASTIC_NET)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)
model.cross_validate_model_performance(x_train=x_train,t_train=t_train)
model.cross_validate_prediction(x_val=x_val,t_val=t_val)

ElasticNetRegression
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.285909  0.284886  0.601984
1  0.7  0.3  0.7  1.0  1.0  1.0  0.285909  0.284886  0.540750
2  0.4  0.8  0.7  1.0  1.0  1.0  0.285909  0.284886  0.528248
3  0.8  0.2  0.8  1.0  1.0  1.0  0.285909  0.284886  0.552438
4  0.0  0.0  0.0  1.0  1.0  1.0  0.285909  0.284886  0.453573
err:  0.35517302040584436
Cross-validation scores:  [0.72473183 0.71480492 0.79531539 0.74385548 0.73560676 0.7654424
 0.72404961 0.81673803 0.76906414 0.75816626]
Mean accuracy: 0.75 (+/- 0.03)
[[ 4.86721716e-01  5.47438649e-01  9.53514805e-01]
 [ 5.09634759e-01  5.11272483e-01  6.23777458e-01]
 [ 6.25164393e-01  5.40090304e-01  7.13411267e-01]
 [ 5.82076514e-01  5.92106149e-01  8.11463475e-01]
 [-4.65218319e-03 -1.05907433e-02  5.66914851e-03]
 [-3.37450760e-02 -1.84594797e-02 -7.31316140e-03]
 [ 5.45450328e-01  5.75477552e-01  9.18483943e-01]
 [ 5.83434830e-03  2.05199858e-02  1.46680729e-02]
 [ 5

array([[ 4.86721716e-01,  5.47438649e-01,  9.53514805e-01],
       [ 5.09634759e-01,  5.11272483e-01,  6.23777458e-01],
       [ 6.25164393e-01,  5.40090304e-01,  7.13411267e-01],
       [ 5.82076514e-01,  5.92106149e-01,  8.11463475e-01],
       [-4.65218319e-03, -1.05907433e-02,  5.66914851e-03],
       [-3.37450760e-02, -1.84594797e-02, -7.31316140e-03],
       [ 5.45450328e-01,  5.75477552e-01,  9.18483943e-01],
       [ 5.83434830e-03,  2.05199858e-02,  1.46680729e-02],
       [ 5.20805286e-01,  5.91800547e-01,  8.71593189e-01],
       [-2.50093063e-03, -1.72266076e-02, -4.17090076e-03],
       [ 2.42177721e-01, -1.20733101e-03,  1.42095401e-02],
       [ 2.69806539e-02,  4.11669243e-02,  1.99006936e-02],
       [ 2.12793452e-03,  5.06959780e-03,  1.02701222e-02],
       [ 3.59176845e-02, -9.80148381e-03,  1.60346839e-02],
       [ 5.22167004e-01,  5.59167124e-01,  1.00956145e+00],
       [ 2.41537576e-02,  4.84034544e-02,  3.20031180e-02],
       [ 5.69027174e-01,  5.46625432e-01

In [14]:
model = RegressionFactory.get_model(RegressionModels.DECISION_TREE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)
model.cross_validate_model_performance(x_train=x_train,t_train=t_train)
model.cross_validate_prediction(x_val=x_val,t_val=t_val)

DecisionTreeRegression
     0    1    2    3    4    5    6    7    8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.2  0.9  1.0
1  0.7  0.3  0.7  1.0  1.0  1.0  0.8  0.1  0.6
2  0.4  0.8  0.7  1.0  1.0  1.0  0.5  0.7  0.7
3  0.8  0.2  0.8  1.0  1.0  1.0  0.8  0.3  0.9
4  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0
err:  0.053939393939393905
Cross-validation scores:  [0.8553837  0.90406657 0.88918411 0.91296766 0.91977559 0.8990333
 0.90192955 0.89685985 0.89814846 0.89180825]
Mean accuracy: 0.90 (+/- 0.02)
[[0.2 0.7 0.9]
 [1.  0.1 0.8]
 [0.5 0.8 0.9]
 [1.  0.1 0.8]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.3 1.  0.9]
 [0.  0.  0. ]
 [0.8 0.5 0.8]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.1 0.3 1. ]
 [0.  0.  0. ]
 [0.3 1.  0.9]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.4 0.9 0.6]
 [1.  0.1 0.9]
 [1.  0.6 0.8]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [0.9 0.8 0.6]
 [0.  0.  0. ]
 [0.  0.  0. ]
 [1.  0.2 2. ]
 [0.5 0.8 2. ]
 [0.4 0.6 1. ]
 [0.

array([[0.2, 0.7, 0.9],
       [1. , 0.1, 0.8],
       [0.5, 0.8, 0.9],
       [1. , 0.1, 0.8],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0.3, 1. , 0.9],
       [0. , 0. , 0. ],
       [0.8, 0.5, 0.8],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0.1, 0.3, 1. ],
       [0. , 0. , 0. ],
       [0.3, 1. , 0.9],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0.4, 0.9, 0.6],
       [1. , 0.1, 0.9],
       [1. , 0.6, 0.8],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0.9, 0.8, 0.6],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [1. , 0.2, 2. ],
       [0.5, 0.8, 2. ],
       [0.4, 0.6, 1. ],
       [0.1, 0.7, 2. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0.7, 1. , 0.7],
       [0.5, 0.8, 2. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. , 0. ],
       [0. , 0. 

In [15]:
model = RegressionFactory.get_model(RegressionModels.LASO)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)
model.cross_validate_model_performance(x_train=x_train,t_train=t_train)
model.cross_validate_prediction(x_val=x_val,t_val=t_val)

LasoRegressione Model
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.285909  0.284886  0.526818
1  0.7  0.3  0.7  1.0  1.0  1.0  0.285909  0.284886  0.526818
2  0.4  0.8  0.7  1.0  1.0  1.0  0.285909  0.284886  0.526818
3  0.8  0.2  0.8  1.0  1.0  1.0  0.285909  0.284886  0.526818
4  0.0  0.0  0.0  1.0  1.0  1.0  0.285909  0.284886  0.526818
err:  0.3783429752066116
Cross-validation scores:  [0.7231409  0.71248399 0.79150087 0.73981045 0.73178551 0.76194023
 0.72002615 0.81182093 0.76877131 0.75133993]
Mean accuracy: 0.75 (+/- 0.03)
[[ 4.70656189e-01  5.27907820e-01  9.27516606e-01]
 [ 5.13064020e-01  5.02254873e-01  6.12700981e-01]
 [ 6.21790327e-01  5.41762678e-01  7.19957991e-01]
 [ 5.83321985e-01  5.74934469e-01  7.97959904e-01]
 [ 7.28121093e-03  1.38455108e-02  7.18296725e-03]
 [-1.55063795e-02  4.74359091e-03 -3.59262249e-03]
 [ 5.40305217e-01  5.56222894e-01  8.92185337e-01]
 [ 9.74768256e-03  7.80976617e-03  1.22781729e-02]
 [ 

array([[ 4.70656189e-01,  5.27907820e-01,  9.27516606e-01],
       [ 5.13064020e-01,  5.02254873e-01,  6.12700981e-01],
       [ 6.21790327e-01,  5.41762678e-01,  7.19957991e-01],
       [ 5.83321985e-01,  5.74934469e-01,  7.97959904e-01],
       [ 7.28121093e-03,  1.38455108e-02,  7.18296725e-03],
       [-1.55063795e-02,  4.74359091e-03, -3.59262249e-03],
       [ 5.40305217e-01,  5.56222894e-01,  8.92185337e-01],
       [ 9.74768256e-03,  7.80976617e-03,  1.22781729e-02],
       [ 5.15447606e-01,  5.57915826e-01,  8.47065352e-01],
       [ 9.05044384e-03,  7.58998620e-03, -1.30900725e-03],
       [ 2.15657507e-01,  4.14273438e-02,  4.10555400e-02],
       [ 3.32419254e-02,  3.66510871e-02,  4.57418731e-02],
       [ 1.53915392e-02,  1.93509905e-02,  3.28640103e-02],
       [ 3.83977025e-02,  1.10419317e-02,  1.15607323e-02],
       [ 5.07080148e-01,  5.35940073e-01,  9.87873390e-01],
       [ 3.17354217e-02,  4.08413272e-02,  5.82341162e-02],
       [ 5.72249985e-01,  5.38814754e-01

In [16]:
model = RegressionFactory.get_model(RegressionModels.RANDOM_FOREST)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)
model.cross_validate_model_performance(x_train=x_train,t_train=t_train)
model.cross_validate_prediction(x_val=x_val,t_val=t_val)

RandomForestRegression
     0    1    2    3    4    5      6      7      8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.219  0.848  0.921
1  0.7  0.3  0.7  1.0  1.0  1.0  0.701  0.328  0.711
2  0.4  0.8  0.7  1.0  1.0  1.0  0.397  0.810  0.728
3  0.8  0.2  0.8  1.0  1.0  1.0  0.813  0.286  0.783
4  0.0  0.0  0.0  1.0  1.0  1.0  0.000  0.000  0.000
err:  0.03548030303030306
Cross-validation scores:  [0.93610695 0.96823177 0.96282209 0.95434619 0.96412526 0.96556829
 0.9494723  0.96829313 0.94914139 0.94953511]
Mean accuracy: 0.96 (+/- 0.01)
[[2.730e-01 7.700e-01 9.070e-01]
 [7.660e-01 4.740e-01 7.270e-01]
 [3.630e-01 7.490e-01 7.640e-01]
 [7.910e-01 3.900e-01 7.980e-01]
 [4.000e-03 2.000e-03 4.000e-03]
 [0.000e+00 0.000e+00 0.000e+00]
 [2.690e-01 7.110e-01 8.760e-01]
 [0.000e+00 0.000e+00 0.000e+00]
 [7.580e-01 4.750e-01 8.630e-01]
 [5.000e-03 8.000e-03 2.000e-02]
 [0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00]
 [1.000e-03 5.000e-03 2.000e-02]
 

array([[2.730e-01, 7.700e-01, 9.070e-01],
       [7.660e-01, 4.740e-01, 7.270e-01],
       [3.630e-01, 7.490e-01, 7.640e-01],
       [7.910e-01, 3.900e-01, 7.980e-01],
       [4.000e-03, 2.000e-03, 4.000e-03],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [2.690e-01, 7.110e-01, 8.760e-01],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [7.580e-01, 4.750e-01, 8.630e-01],
       [5.000e-03, 8.000e-03, 2.000e-02],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [1.000e-03, 5.000e-03, 2.000e-02],
       [2.500e-01, 4.760e-01, 8.750e-01],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [3.320e-01, 7.430e-01, 7.700e-01],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [0.000e+00, 0.000e+00, 0.000e+00],
       [4.180e-01, 7.260e-01, 7.470e-01],
       [7.990e-01, 4.230e-01, 7.420e-01],
       [7.600e-01, 5.210e-01, 9.35

In [87]:
model = RegressionFactory.get_model(RegressionModels.RIDGE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)
model.cross_validate_model_performance(x_train=x_train,t_train=t_train)
model.cross_validate_prediction(x_val=x_val,t_val=t_val)

RidgeRegressionl
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.273684  0.962511  0.998222
1  0.7  0.3  0.7  1.0  1.0  1.0  0.547760  0.671676  0.683041
2  0.4  0.8  0.7  1.0  1.0  1.0  0.445369  0.868847  0.715650
3  0.8  0.2  0.8  1.0  1.0  1.0  0.758729  0.237631  0.784300
4  0.0  0.0  0.0  1.0  1.0  1.0 -0.036772 -0.232032  0.026490
err:  0.12186584413541035


array([[19.59696584,  9.72658211,  2.02521912]])