In [25]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [27]:
import seaborn as ss
import numpy as np
from manager.data import DataManager
from factory.classfication_factory import ClassificationFactory
from factory.regression_factory import RegressionFactory
from constants.classification_models import ClassificationModels
from constants.regression_models import RegressionModels



In [28]:
data_manager = DataManager(min_sample_label=10)

data, x_train, x_val, t_train, t_val, = data_manager.get_data()

# accorderie = [[633, 6865, 10, 0, 0.02, 4.04, 0.05, 4.86, 0.06, 75.33]]
accorderie = np.array([[0,100.0,500.0,7.0,0.0,0.0505050505050505,3.263549415515409,0.124,5.24,0.153466632043625,61.42,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,4.0,2.0,2.0,1.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,3.0,2.0,2.0,1.0,4.0,2.0,2.0,1.0,11.0,6.0,6.0,3.0,2.0,1.0,2.0,1.0,2.0,1.0,6.0,3.0,4.0,2.0,2.0,1.0,2.0,1.0,6.0,3.0,4.0,2.0,7.0,4.0,2.0,1.0,2.0,1.0,4.0,2.0,4.0,2.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,4.0,2.0,6.0,3.0,2.0,1.0,2.0,1.0,2.0,1.0,4.0,2.0,2.0,1.0,2.0,1.0,3.0,2.0,6.0,3.0,2.0,1.0,4.0,2.0,2.0,1.0,4.0,2.0,8.0,4.0,5.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,8.0,4.0,7.0,4.0,4.0,2.0,2.0,1.0,2.0,1.0,7.0,4.0,4.0,2.0,9.0,5.0,6.0,3.0,4.0,2.0,6.0,3.0,10.0,5.0,2.0,1.0,6.0,3.0,4.0,2.0,4.0,3.0,4.0,2.0,4.0,2.0,4.0,2.0,6.0,3.0,2.0,1.0,2.0,1.0,10.0,5.0,4.0,2.0,6.0,3.0,8.0,4.0,8.0,4.0,14.0,7.0,12.0,6.0,4.0,2.0,4.0,2.0,8.0,4.0,6.0,3.0,8.0,4.0,4.0,2.0,4.0,2.0,4.0,2.0,4.0,2.0,11.0,6.0,2.0,1.0,10.0,5.0,6.0,3.0,7.0,4.0,6.0,3.0,6.0,3.0,2.0,1.0,2.0,1.0,8.0,4.0,8.0,4.0,10.0,5.0,6.0,3.0,9.0,5.0,7.0,4.0,10.0,5.0,9.0,5.0,4.0,2.0,14.0,7.0,10.0,5.0,4.0,2.0,6.0,3.0,2.0,1.0,8.0,4.0,6.0,3.0,8.0,4.0,4.0,2.0,6.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,6.0,3.0,4.0,2.0,4.0,2.0,2.0,1.0,8.0,5.0,7.0,4.0,14.0,7.0,6.0,3.0,6.0,3.0,10.0,5.0,14.0,8.0,11.0,6.0,2.0,1.0,6.0,3.0,14.0,7.0,8.0,4.0,6.0,3.0,2.0,1.0,6.0,3.0,13.0,7.0,5.0,3.0,5.0,3.0,12.0,7.0,8.0,4.0,12.0,6.0,8.0,4.0,8.0,4.0,15.0,8.0,10.0,5.0,12.0,6.0,8.0,4.0,11.0,6.0,10.0,5.0,6.0,3.0,11.0,6.0,9.0,5.0,11.0,6.0,2.0,1.0,14.0,7.0,2.0,1.0,2.0,1.0,4.0,2.0,8.0,4.0,8.0,4.0,8.0,4.0,8.0,4.0,2.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.333333333333333,0.3333333333333333,0.7777777777777777,0.3333333333333333,0.0,1.0,0.0,2.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.09090909090909091,0.0,0.6363636363636364,0.0,1.333333333333333,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.142857142857143,0.5,0.9047619047619048,0.1428571428571429,0.0,0.4285714285714285,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.333333333333333,0.3333333333333333,0.7777777777777777,0.3333333333333333,0.0,1.0,0.0,2.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.2,0.2,0.8666666666666666,0.2,0.0,0.8,0.0,1.666666666666667,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.111111111111111,0.1111111111111111,0.9259259259259258,0.1111111111111111,0.0,0.6666666666666666,0.0,1.4,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.5,0.5,0.625,0.25,0.0,1.5,0.0,3.333333333333333,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.090909090909091,0.5,0.9393939393939393,0.09090909090909091,0.0,0.5454545454545454,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666666,0,0.5,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.5555555555555556,0.0,1.0,1.142857142857143,0.1428571428571428,0.9047619047619048,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.4444444444444444,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.25,0.125,0.8333333333333333,0.125,0.0,0.625,0.0,1.4,1.142857142857143,0.1428571428571428,0.9047619047619049,0.1428571428571428,0.0,0.7142857142857143,0.0,1.5,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.142857142857143,0.07142857142857142,0.9047619047619048,0.07142857142857142,0.0,0.6428571428571429,0.0,1.25,1.090909090909091,0.5,0.9393939393939393,0.09090909090909088,0.0,0.4545454545454545,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.076923076923077,0.07692307692307693,0.9487179487179487,0.07692307692307691,0.0,0.6153846153846154,0.0,1.285714285714286,1.2,0.5,0.8666666666666666,0.2,0.0,0.4,0.0,1.0,1.2,0.2,0.8666666666666666,0.2,0.0,0.8,0.0,1.666666666666667,1.166666666666667,0.1666666666666667,0.875,0.08333333333333333,0.0,0.8333333333333334,0.0,2.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.066666666666667,0.06666666666666667,0.9555555555555555,0.06666666666666668,0.0,0.6,0.0,1.25,1.0,0.5,1.0,0.09999999999999998,0,0.5,0.0,1.0,1.0,0.5,1.0,0.08333333333333333,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.090909090909091,0.5,0.9393939393939393,0.09090909090909088,0.0,0.4545454545454545,0.0,1.0,1.0,0.5,1.0,0.09999999999999999,0,0.5,0.0,1.0,1.0,0.5,1.0,0.1666666666666667,0,0.5,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.09090909090909088,0.0,0.6363636363636364,0.0,1.333333333333333,1.111111111111111,0.5,0.9259259259259258,0.1111111111111111,0.0,0.5555555555555556,0.0,1.0,1.090909090909091,0.09090909090909091,0.9393939393939393,0.0909090909090909,0.0,0.6363636363636364,0.0,1.333333333333333,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.07142857142857141,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0,1.0,0.5,1.0,0.25,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.125,0,0.5,0.0,1.0,1.0,0.5,1.0,0.5,0,0.5,0.0,1.0]])


training_set_size = x_train.shape[1]
accorderie_size = np.array(accorderie).shape[1]

if training_set_size > accorderie_size:
    diff = training_set_size - accorderie_size
    accorderie = np.array([np.concatenate([accorderie[0],np.zeros(diff)])])
else:
    accorderie = np.array([accorderie[0][:x_train.shape[1]]])

print(accorderie.shape, x_train.shape)



(1, 1038) (880, 1038)


In [30]:
model = RegressionFactory.get_model(RegressionModels.ELASTIC_NET)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

ElasticNetRegression
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.285909  0.284886  0.601984
1  0.7  0.3  0.7  1.0  1.0  1.0  0.285909  0.284886  0.540750
2  0.4  0.8  0.7  1.0  1.0  1.0  0.285909  0.284886  0.528248
3  0.8  0.2  0.8  1.0  1.0  1.0  0.285909  0.284886  0.552438
4  0.0  0.0  0.0  1.0  1.0  1.0  0.285909  0.284886  0.453573
err:  0.35517302040584436


array([[0.28590909, 0.28488636, 6.22115044]])

In [67]:
model = RegressionFactory.get_model(RegressionModels.DECISION_TREE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

DecisionTreeRegression
     0    1    2    3    4    5    6    7    8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.3  0.7  1.0
1  0.7  0.3  0.7  1.0  1.0  1.0  0.8  0.2  0.6
2  0.4  0.8  0.7  1.0  1.0  1.0  0.5  0.7  0.6
3  0.8  0.2  0.8  1.0  1.0  1.0  0.8  0.3  0.9
4  0.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0
err:  0.05469696969696967


array([[0., 0., 0.]])

In [88]:
model = RegressionFactory.get_model(RegressionModels.LASO)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)


LasoRegressione Model
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.285909  0.284886  0.526818
1  0.7  0.3  0.7  1.0  1.0  1.0  0.285909  0.284886  0.526818
2  0.4  0.8  0.7  1.0  1.0  1.0  0.285909  0.284886  0.526818
3  0.8  0.2  0.8  1.0  1.0  1.0  0.285909  0.284886  0.526818
4  0.0  0.0  0.0  1.0  1.0  1.0  0.285909  0.284886  0.526818
err:  0.3783429752066116


array([[0.28590909, 0.28488636, 0.52681818]])

In [82]:
model = RegressionFactory.get_model(RegressionModels.RANDOM_FOREST)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

RandomForestRegression


KeyboardInterrupt: 

In [87]:
model = RegressionFactory.get_model(RegressionModels.RIDGE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

RidgeRegressionl
     0    1    2    3    4    5         6         7         8
0  0.3  1.0  1.0  1.0  1.0  1.0  0.273684  0.962511  0.998222
1  0.7  0.3  0.7  1.0  1.0  1.0  0.547760  0.671676  0.683041
2  0.4  0.8  0.7  1.0  1.0  1.0  0.445369  0.868847  0.715650
3  0.8  0.2  0.8  1.0  1.0  1.0  0.758729  0.237631  0.784300
4  0.0  0.0  0.0  1.0  1.0  1.0 -0.036772 -0.232032  0.026490
err:  0.12186584413541035


array([[19.59696584,  9.72658211,  2.02521912]])