In [15]:
%load_ext autoreload 
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [57]:
import seaborn as ss
from manager.data import DataManager
from factory.classfication_factory import ClassificationFactory
from factory.regression_factory import RegressionFactory
from constants.classification_models import ClassificationModels
from constants.regression_models import RegressionModels



In [58]:
data_manager = DataManager(min_sample_label=10)

data, x_train, x_val, t_train, t_val, = data_manager.get_data()

accorderie = [[10, 0, 0.02, 4.04, 0.05, 4.86, 0.06, 75.33]]

In [37]:
print(t_val.shape)

(267, 1)


In [ ]:
ss.heatmap(data.corr().fillna(0), cmap="YlGnBu", annot=True, vmin=-1, vmax=1,linewidths=.5, cbar=True, square=True, fmt='.1f')

In [ ]:
ss.pairplot(data)

In [ ]:
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import numpy as np

pca = PCA(n_components=2)
X = data.iloc[:,:-3]
y = data.iloc[:, -3:]

X = StandardScaler().fit_transform(X)

X_pca = pca.fit_transform(X)

columns = y.shape[1]
print(y.shape)
fig, axes = plt.subplots(2, columns)
print()
for i in range(columns):
    axes[0, i].scatter(X_pca[:,0], X_pca[:,1], c=y.iloc[:,i], label=np.unique(y.iloc[:,i]))
    axes[0, i].set_xlabel("Principal Component 1")
    axes[0, i].set_ylabel("Principal Component 2")
    axes[0, i].set_title(f"Target variable {i+1}")
    
    axes[1, i].hist(y.iloc[:, i], bins=20)
    axes[1, i].set_xlabel("Target value")
    axes[1, i].set_ylabel("Frequency")
    
# fig.tight_layout()
plt.legend()
# plt.colorbar()
plt.show()


In [59]:
model = RegressionFactory.get_model(RegressionModels.ELASTIC_NET)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

ElasticNetRegression
Accuracy:  0.1577938708488364


array([[0.49821429, 0.58599624, 0.67969925]])

In [61]:
model = RegressionFactory.get_model(RegressionModels.DECISION_TREE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

DecisionTreeRegression
Error:  0.20775280898876416


array([[0.4, 0.1, 2. ]])

In [62]:
model = RegressionFactory.get_model(RegressionModels.LASO)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

LasoRegressione Model
Error:  0.1577938708488364


array([[0.49821429, 0.58599624, 0.67969925]])

In [63]:
model = RegressionFactory.get_model(RegressionModels.RANDOM_FOREST)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

RandomForestRegression
Error:  0.12356094382022464


array([[0.44 , 0.198, 1.22 ]])

In [64]:
model = RegressionFactory.get_model(RegressionModels.RIDGE)

model.train(x_train=x_train,x_val=x_val,t_train=t_train,t_val=t_val)
model.predict(x_val=accorderie)

RidgeRegressionl
Error:  0.10531772337920751


array([[ 0.250496  , -2.54423007,  0.28662204]])